pre-push:
    - swift test
pre-commit:
    - swift run -c release --package-path BuildTools swiftformat .
    - run:
        command: swift run -c release --package-path BuildTools swiftlint lint .
        critical: false